# 機器人設定檔
bot:
  token: ""
  # 如果你不知道如何獲得你的伺服器 ID，請使用指令 /getid
  guildId: "-1"

# 若啟用，指令將會被記錄在主控制台中
logCommands: false

# 在此清單中的指令將會被停用
disabledCommands:
  - "shutdown"

# Discord 指令將會回覆成暫時性訊息
# 暫時性訊息將只能由指令執行者看見（如果有啟用上方的設定，它們將仍然會被記錄下來）
ephemeral:
  - "addons"
  - "getid"

# 要求使用身分組來執行指令
# 成員將被要求最少一個身分組
#
# 範例
# roles:
#   # 指令名稱
#   addons:
#     - "ROLE_ID"
roles: []

# 你必須放置頻道 ID 在下方，不是頻道名稱
announcements:
  researchUnlock: ""

# 自動更新
auto-update: true

# 除錯模式
debug: false