# Bot Configuration
bot:
  token: ""
  # If you do not know how to get your guild id, use the command /getid
  guildId: "-1"

# Commands in this list will be disabled
disabledCommands:
  - "shutdown"

# You need to place the channel id below, NOT the name
announcements:
  researchUnlock: ""

# Debug Mode
debug: fales