# 機器人設定
bot:
  token: ""
  # 如果你不知道如何獲取你自己的 Discord 伺服器ID, 可以在伺服器中使用此指令 /getid
  guildId: "-1"

# 此列表中的指令將會被停用
disabledCommands:
  - "shutdown"

# 你必須在底下放置頻道ID, 而不是頻道名稱
announcements:
  researchUnlock: ""

# Debug 模式
debug: fales