name: ${project.name}
description: ${project.description}

main: tsp.slimebot.SlimeBot
version: Build - ${number}
author: Silent
depend: [Slimefun]

commands:
  slimebot:
    usage: /slimebot
    description: Plugin Information